DB : 
  db_database : ${DB_NAME}
  db_user : ${DB_USER}
  db_password : ${DB_PASSWORD}
  db_host : ${DB_HOST}
  db_port : ${DB_PORT}
  db_table : ${DB_TABLE}

DB_VPS :
  db_database : ${DB_NAME_VPS}
  db_user : ${DB_USER_VPS}
  db_password : ${DB_PASSWORD_VPS}
  db_host : ${DB_HOST_VPS}
  db_port : ${DB_PORT_VPS}
  db_table : ${DB_TABLE_VPS}

CONNECTION :
  winamax : 
    connection_username : ${WINAMAX_USER}
    connection_password : ${WINAMAX_PASSWORD}
    connection_day : ${DAY}
    connection_month : ${MONTH}
    connection_year : ${YEAR}
    amount_golden : 10
    amount_silver : 2
  PSEL : 
    connection_username : ${PSEL_USER}
    connection_password : ${PSEL_PASSWORD}
    connection_day : ${DAY}
    connection_month : ${MONTH}
    connection_year : ${YEAR}
    amount_golden : 2
    amount_silver : 1

MLFLOW:
  tracking_uri: "http://localhost:5002"
  experiment_name: "Bio inspired AI Project Coefficients"
  run_name: "Run 3 model 1"

PREPARE_DATA:
  text_embedding_method: 'camembert'  # Options: 'camembert', 'tfidf''
  use_class_token: True
  test_size: 0.2
  val_size: 0.2
  chronological_split: False
  random_state: 42
  batch_size_embedding: 128
  threshold_sports: 100
  only_golden: False
  without_golden: False
  with_feature_is_golden: False

AI_MODEL_CONFIGS:
  config_1:
    model_name: "logistic_regression"
  config_2:
    model_name: "simple_nn"
  config_3:
    model_name: "deep_resnet" 
  config_4:
    model_name: "attention_nn"

TRAINING:
  epochs: 40
  batch_size: 64
  learning_rate: 0.000005
  patience: 15
  coefficient_ce_loss: 0.33
  coefficient_profit_loss: 0.33
  coefficient_small_preds_loss: 0.33

TESTING:
  test_batch_size: 64
  test_coefficient_ce_loss: 0.33
  test_coefficient_profit_loss: 0.33
  test_coefficient_small_preds_loss: 0.33
  test_visualization_best_worst: False # Choose between "True" or "False"

config_number: 3 # Choose between 1, 2, 3 or 4

EVOLUTIONARY_ALGORITHM:
  population_size: 10
  generations: 20
  pm: 0.2
  pc: 0.4
  mutation_std_dev: 0.2

BO:
  headless : False
  user_agents:
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
    - "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.172"
    - "Mozilla/5.0 (X11; Debian; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/90.0.4430.212 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Vivaldi/4.1.2369.21"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.864.64 Safari/537.36 Edg/91.0.864.64"
    - "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"

TELEGRAM:
  token : ${TELEGRAM_BOT_TOKEN}
  chat_id : ${TELEGRAM_CHAT_ID}

SPECIFIC :
  token_telegram_add_sport : ${TELEGRAM_BOT_TOKEN_ADD_SPORT}
  global_retrieve : False # Choose between "True" or "False"
  metals : ["gold", "silver"]
  add_sport : "manual" # Choose between "telegram" or "manual"
  table_name : "betclic" # Chose between "winamax" or "PSEL" or "betclic"


# python3 analyze_data/main_analyze_data.py --config_path config/config_gagou.yaml --env_path config/.env.gagou