MODEL_PARAMETERS:
  config_number:
    type: choice
    values: [1, 2, 3, 4]

TRAINING_PARAMETERS:
  learning_rate:
    type: loguniform
    low: 0.00000001
    high: 0.00001
  coefficient_ce_loss:
    type: uniform
    low: 0.1
    high: 1.0
  coefficient_profit_loss:
    type: uniform
    low: 0.1
    high: 0.6
  coefficient_small_preds_loss:
    type: uniform
    low: 0.1
    high: 0.3